// <auto-generated />
using System;
using HouseholdPlantsManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace HouseholdPlantsManagement.Migrations
{
    [DbContext(typeof(PlantContext))]
    [Migration("20240804101502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("HouseholdPlantsManagement.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FertilizingInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFertilized")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWatered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WateringInterval")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FertilizingInterval = 30,
                            ImageUrl = "http://example.com/fiddle-leaf-fig.jpg",
                            LastFertilized = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastWatered = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fiddle Leaf Fig",
                            Notes = "Needs bright, indirect light.",
                            PurchaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Species = "Ficus lyrata",
                            WateringInterval = 7
                        },
                        new
                        {
                            Id = 2,
                            FertilizingInterval = 60,
                            ImageUrl = "http://example.com/snake-plant.jpg",
                            LastFertilized = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastWatered = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snake Plant",
                            Notes = "Very low maintenance.",
                            PurchaseDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Species = "Sansevieria trifasciata",
                            WateringInterval = 14
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
